version: '3'

services:
        webapp:
                build: ./webapp/
                volumes:
                        - run-volume:/run
                        - static-volume:/code/static/
        collector-orchestrator:
                build: ./collection/
        collector:
                build: ./collection/collector/
        postgres:
                image: "postgres"
                # restart: always
                environment:
                        - POSTGRES_PASSWORD:password
                volumes:
                        - postgres-data:/var/lib/postgresql/data
        influxdb:
                image: "influxdb"
                ports:
                        - "8086:8086"
                volumes:
                        - influx-data:/var/lib/influxdb

        nginx:
                image: "nginx"
                volumes:
                        - ./webapp/nginx.conf:/etc/nginx/nginx.conf
                        - run-volume:/run
                        - static-volume:/code/static/
                ports:
                        - "80:80"
                        #  - "443:443"
        grafana:
                image: "grafana/grafana"
                volumes:
                        - ./grafana/grafana.ini:/etc/grafana/grafana.ini
                        - grafana-data:/var/lib/grafana
                ports:
                        - "3000:3000"
        alert_generation:
                build: ./alert_generation/
        socketio_server:
                build: ./alert_generation/socketio_server/
                ports:
                        - "443:443"

volumes:
        run-volume:  # To share the gunicorn sock
        grafana-data:  # To persist grafana db
        influx-data:  # To persist influx db
        static-volume: # To share the static files for Flask with Nginx
        postgres-data: # To persist postgre db
