version: '3'

services:
        webapp:
                build: ./webapp/
                volumes:
                        - run-volume:/run
        collector-orchestrator:
                build: ./collection/
                ports:
                        - "5557:5557"
        collector:
                build: ./collection/collector/
        postgres:
                image: "postgres"
        influxdb:
                image: "influxdb"
                ports:
                        - "8086:8086"
                volumes:
                        - influx-data:/var/lib/influxdb

        nginx:
                image: "nginx"
                volumes:
                        - ./webapp/nginx.conf:/etc/nginx/nginx.conf
                        - run-volume:/run
                ports:
                        - "80:80"
                        - "443:443"
        grafana:
                image: "grafana/grafana"
                volumes:
                        - ./grafana/grafana.ini:/etc/grafana/grafana.ini
                        - grafana-data:/var/lib/grafana
                ports:
                        - "3000:3000"

volumes:
        run-volume:  # To share the gunicorn sock
        grafana-data:  # To persist grafana db
        influx-data:  # To persist influx db
