DROP TABLE IF EXISTS EMAIL_NOTIFICATION;
DROP TABLE IF EXISTS NOTIFICATION;
DROP TABLE IF EXISTS PRICE_POINT_ALERT;
DROP TABLE IF EXISTS ALERT;
DROP TABLE IF EXISTS REGISTERED_USER;

CREATE TABLE IF NOT EXISTS REGISTERED_USER(
  user_pk SERIAL PRIMARY KEY,
  user_name VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS ALERT(
  alert_pk SERIAL PRIMARY KEY,
  created_by_user INTEGER REFERENCES REGISTERED_USER(user_pk),
  fulfilled BOOL NOT NULL,
  repeat BOOL NOT NULL
);

CREATE TABLE IF NOT EXISTS NOTIFICATION(
  notification_pk SERIAL PRIMARY KEY,
  notify_on_which_alert INTEGER REFERENCES ALERT(alert_pk)
);

CREATE TABLE IF NOT EXISTS EMAIL_NOTIFICATION(
  user_to_notify INTEGER REFERENCES REGISTERED_USER(user_pk)
) INHERITS(NOTIFICATION);

CREATE TABLE IF NOT EXISTS PRICE_POINT_ALERT(
  exchange VARCHAR(100) NOT NULL,
  pair VARCHAR(20) NOT NULL,
  point REAL NOT NULL,
  direction VARCHAR(20) NOT NULL CHECK (direction IN ('up', 'down'))
) INHERITS(ALERT);