DROP TABLE IF EXISTS EMAIL_NOTIFICATION;
DROP TABLE IF EXISTS NOTIFICATION;
DROP TABLE IF EXISTS PRICE_POINT_ALERT;
DROP TABLE IF EXISTS VOLUME_POINT_ALERT;
DROP TABLE IF EXISTS PRICE_PERCENTAGE_ALERT;
DROP TABLE IF EXISTS ALERT;
DROP TABLE IF EXISTS REGISTERED_USER;

CREATE TABLE IF NOT EXISTS REGISTERED_USER(
  user_pk SERIAL PRIMARY KEY,
  user_name VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS ALERT(
  alert_pk SERIAL PRIMARY KEY,
  created_by_user INTEGER REFERENCES REGISTERED_USER(user_pk),
  fulfilled BOOL NOT NULL,
  repeat BOOL NOT NULL
);

CREATE TABLE IF NOT EXISTS NOTIFICATION(
  notification_pk SERIAL PRIMARY KEY,
  notify_on_which_alert INTEGER REFERENCES ALERT(alert_pk)
);

CREATE TABLE IF NOT EXISTS EMAIL_NOTIFICATION(
  user_to_notify INTEGER REFERENCES REGISTERED_USER(user_pk)
) INHERITS(NOTIFICATION);

CREATE TABLE IF NOT EXISTS PRICE_POINT_ALERT(
  exchange VARCHAR(100) NOT NULL,
  pair VARCHAR(20) NOT NULL,
  point REAL NOT NULL,
  direction VARCHAR(20) NOT NULL CHECK (direction IN ('up', 'down'))
) INHERITS(ALERT);

CREATE TABLE IF NOT EXISTS VOLUME_POINT_ALERT(
  exchange VARCHAR(100) NOT NULL,
  pair VARCHAR(20) NOT NULL,
  point REAL NOT NULL
) INHERITS(ALERT);

CREATE TABLE IF NOT EXISTS PRICE_PERCENTAGE_ALERT(
  exchange VARCHAR(100) NOT NULL,
  pair VARCHAR(20) NOT NULL,
  point REAL NOT NULL,
  direction VARCHAR(20) NOT NULL CHECK (direction IN ('up', 'down')),
  time_frame REAL NOT NULL
) INHERITS(ALERT);

CREATE UNLOGGED TABLE IF NOT EXISTS ORDER_BOOK (
  snapshot_time BIGINT NOT NULL,
  exchange TEXT NOT NULL,
  market TEXT NOT NULL,
  book JSON NOT NULL,

  PRIMARY KEY(snapshot_time, exchange, market)
);