#
#
#  Need to set REST IP in graylog config also.
#
#

version: '3.5'

services:
    mongo:
            image: "mongo:3"
            restart: always
            #volumes:
                    #- mongo:/data/db
    elasticsearch:
            image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.5.4
            restart: always
            environment:
                    - http.host=0.0.0.0
                    - transport.host=localhost
                    - network.host=0.0.0.0
                    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            #volumes:
                    #- elasticsearch:/usr/share/elasticsearch/data
    graylog:
            #image: graylog/graylog:3.0.0-beta.3-1
            image: graylog/graylog:2.5
            restart: always
            volumes:
                    - ./data/journal:/usr/share/graylog/data/journal
                    - ./config:/usr/share/graylog/data/config
            #environment:
                    #GRAYLOG_PASSWORD_SECRET: senhadeexemplo123123123123
                    #GRAYLOG_ROOT_PASSWORD_SHA2: fec576ecc231a923f56df2b8695df21087324a951fc1beff2af9a42d3bb6f9d1
                    #GRAYLOG_WEB_ENDPOINT_URI: http://0.0.0.0:9000/api/
                    #GRAYLOG_HTTP_BIND_ADDRESS: 0.0.0.0:9000  # Graylog 3
            depends_on:
                    - mongo
                    - elasticsearch
            ports:
                    - "9000:9000" # Graylog frontend
                    - "9001:9001" # Graylog REST api
                    - "12201:12201/udp"
                    - "1514:1514"
                    - "514:514/udp"


volumes:
        run-volume:  # To share the gunicorn sock
        grafana-data:  # To persist grafana db
        influx-data:  # To persist influx db
        static-volume: # To share the static files for Flask with Nginx
        postgres-data: # To persist postgre db
        elasticsearch:
        mongo:

networks:
  default:
    external:
      name: globalnet
